### PR TITLE
Release 2.16.0 - absolute paths

### PR DESCRIPTION
**Pull request by j-d-carmichael**
Aim to release 2.16.0 by 10th Sept.

Ref.:  https://github.com/liffery-com/boats/pull/54

### CODE REVIEW

**Comment by j-d-carmichael** [comment]
There was 1 small glitch fixed here: https://github.com/liffery-com/boats/commit/8b9f2fbd89857538ceeed7673320bfa1201267a9

When there was no paths objects set in the boatsrc file it failed - this sets an empty object in such a case

**Comment by TomFreeman** [comment]
Thanks for the fix!

**Comment by j-d-carmichael** [comment]
@TomFreeman  I have been running with your new paths feature yesterday and today.. no more issues have come up :+1:   so i think i will release this now. This is a great feature addition! Thanks again

**Comment by j-d-carmichael** [comment]
@TomFreeman  sods law.. i released then spotted an issue  https://github.com/liffery-com/boats/issues/56

**Comment by j-d-carmichael** [comment]
This feature is so such a time saver :D i'm just adding the replace all into the mix now

**Pull request merged**
